name: Deploy to Heroku

on:
  push:
    branches:
      - main # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      # Step 4: Build the application
      - name: Build the app
        run: pnpm run build

      # Step 5: Deploy to Heroku via Container Registry
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          # Install the Heroku CLI
          curl https://cli-assets.heroku.com/install.sh | sh

          # Login to Heroku Container Registry
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

          # Build and Push Docker Image
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

          # Release the Docker Image
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

      # Step 6: Post-deploy health check
      - name: Health check
        run: |
          curl -f https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/ || exit 1
